controller_names:
  - fake_lss_arm_controller
  - fake_gripper_controller

fake_lss_arm_controller:
    joints:
      - virtual_joint
      - joint0
      - joint1
      - joint2
      - joint3

fake_gripper_controller:
    joints:
      - gripper_r
      - gripper_l
      
initial:
   lss_arm: home
   gripper: open
