controller_manager:
  ros__parameters:
    # update_rate: 15  # Hz
    # diagnostic_period: 1
    update_rate: 100  # Hz

    lss_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # lss_effort_controller:
    #   type: effort_controllers/JointTrajectoryController

    lss_gripper_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


lss_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint0
      - joint1
      - joint2
      - joint3

# lss_effort_controller:
#   ros__parameters:
#   command_interfaces:
#       - effort
#   state_interfaces:
#       - position
#       - velocity
#   joints:
#     - virtual_joint
#     - joint0
#     - joint1
#     - joint2
#     - joint3

lss_gripper_controller:
  ros__parameters:
    joint: gripper_r
