controller_names:
  - joint_trajectory_controller
  - gripper_trajectory_controller
  # - gripper_action_controller
  
joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - lss_arm_joint0
    - lss_arm_joint1
    - lss_arm_joint2
    - lss_arm_joint3

gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - lss_arm_gripper_r
    - lss_arm_gripper_l

# ----- Gripper action controller (not yet functional)
# gripper_action_controller:
#   action_ns: gripper_cmd
#   type: GripperCommand
#   default: true
#   joints:
#     - panda_finger_joint1
#
# Note: Once implemented, the following config needs to be within controller parameters
# controller_manager:
#   ros__parameters:
#     gripper_action_controller:
#       type: position_controllers/GripperActionController
# gripper_action_controller:
#   ros__parameters:
#     joint: panda_finger_joint1
#
# Node: Remember to enable mimicking of finger joints before attempting to use gripper action
