controller_names:
  - joint_trajectory_controller
  - gripper_trajectory_controller
  # - gripper_action_controller
  
joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - lss_arm_joint1
    - lss_arm_joint2
    - lss_arm_joint3
    - lss_arm_joint4

gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - lss_arm_gripper_r
    - lss_arm_gripper_l